/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-input-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {ControlStateMixin} from '@anypoint-web-components/anypoint-control-mixins/control-state-mixin.js';

import {ValidatableMixin} from '@anypoint-web-components/validatable-mixin/validatable-mixin.js';

export {AnypointInputMixin};
