/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   AnypointMaskedInput.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {TemplateResult, SVGTemplateResult} from 'lit-element';

import {AnypointInput} from './AnypointInput';

export {AnypointMaskedInput};

declare class AnypointMaskedInput extends AnypointInput {
  readonly _inputType: string;
  readonly _visibilityToggleIcon: SVGTemplateResult;
  readonly _visibilityToggleTitle: string;
  readonly _visibilityToggleLabel: string;
  _suffixTemplate(): TemplateResult;

  /**
   * Toggles `visible` property value.
   */
  toggleVisibility(): void;
}
